### ISSUE TITLE
office 2019 可以用不？

### ISSUE THREAD

**Issue by lyhrobin00007** [iddddg/KMS-Windows#1]
office 2019 可以用不？

**Comment by iddddg** [comment]
![image](https://user-images.githubusercontent.com/17894764/100815689-81511e00-347f-11eb-8be5-09eecb9aeb52.png)
本来可以，现在服务已经关闭了，巨硬已经不止一次投诉我了。可以搜索引擎搜索，关键字Office 2019 KMS
